version: "3.2"
services:
        web:
                build:
                        dockerfile: Dockerfile
                        context: .
                ports: 
                - "80:8080"
                volumes: 
                        - type: bind
                          source: /home/ubuntu/.m2
                          target: /root/.m2
        db:
                image: mariadb:10.1
                ports:
                        - "3306:3306"
                environment: 
                        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
